# Generated by Django 3.2.4 on 2021-06-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('olymp_prog', '0003_training_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='status',
            field=models.IntegerField(choices=[(1, 'started'), (2, 'ended')], default=1),
        ),
    ]
