# Generated by Django 3.2.4 on 2021-06-08 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('olymp_prog', '0004_alter_training_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_solution',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       help_text='Time of last successful solution to this task',
                                       verbose_name='last solve'),
        ),
        migrations.AddField(
            model_name='task',
            name='last_try',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       help_text='Time of last solution attempt (successful or not)',
                                       verbose_name='last try'),
        ),
        migrations.AddField(
            model_name='task',
            name='solutions_count',
            field=models.IntegerField(default=0, help_text='Number of successful solutions to this task',
                                      verbose_name='Solutions count'),
        ),
        migrations.AlterField(
            model_name='task',
            name='link',
            field=models.URLField(blank=True, help_text='URL to the testing system with the task', verbose_name='link'),
        ),
    ]
