# Generated by Django 3.2.4 on 2021-06-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('olymp_prog', '0005_auto_20210608_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag display name', max_length=64)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(help_text='Tags to this task', related_name='tags', to='olymp_prog.Tag'),
        ),
    ]
