# Generated by Django 3.2.4 on 2021-06-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('olymp_prog', '0007_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags to this task', related_name='tags',
                                         to='olymp_prog.Tag'),
        ),
    ]
