# Generated by Django 3.2.4 on 2021-06-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('olymp_prog', '0008_alter_task_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Full description of the task', max_length=1000,
                                   verbose_name='description'),
        ),
    ]
