# Generated by Django 3.2.4 on 2021-06-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('olymp_prog', '0009_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attempts_count',
            field=models.IntegerField(default=0, help_text='Number of solution attempts to this task'),
        ),
    ]
