# Generated by Django 3.2.4 on 2021-06-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('olymp_prog', '0010_task_attempts_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional info about task'),
        ),
    ]
