# Generated by Django 3.2.4 on 2021-10-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbotsettings',
            name='time_interval_auto_renewal',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userbotsettings',
            name='study_plan_days_duration_time_interval',
            field=models.PositiveSmallIntegerField(default=0, help_text='Amount of days in one time interval'),
        ),
        migrations.AlterField(
            model_name='userbotsettings',
            name='study_plan_hours',
            field=models.PositiveSmallIntegerField(default=0,
                                                   help_text='Amount of hours during user plans to study in specified time interval'),
        ),
    ]
