# Generated by Django 3.2.4 on 2021-11-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20211031_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeinterval',
            name='status',
            field=models.IntegerField(choices=[(1, 'Running'), (2, 'Completed'), (3, 'Failed'), (4, 'On Hold'), (5, 'Terminated With Refund'), (6, 'Terminated Without Refund'), (7, 'Terminated Premature')], default=1),
        ),
    ]
